# site name
prefixName: Hello!
siteName: 张百万
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://www.zhenwen66.cn
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.0
pjax: 1
# 1开启
mathjax: 0

notice: 个人博客刚刚创立，目前正在折腾中...
lazyloadImg: https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.0/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /album/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  #友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    #主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  #客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(9).jpg
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(10).jpg
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(11).jpg
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(12).jpg
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(13).jpg
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(14).jpg
  - https://cdn.jsdelivr.net/gh/ZhangZhenwen/cdn@1.0.2/img/cover/(15).jpg



# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/27307941, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 振文的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 07/15/2020

#social  url, img PC端配置
social:
  github: {url: http://github.com/ZhangZhenwen, img: /img/social/github.png}
  sina: {url: https://weibo.com/1950556371/profile?rightmod=1&wvr=6&mod=personinfo, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=279933865, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/zhang-bai-mo-26, img: /img/social/zhihu.png}
  email: {url: https://mail.163.com/, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/ZhangZhenwen, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/1950556371/profile?rightmod=1&wvr=6&mod=personinfo, fa: fa-weibo, color: dd4b39}
  qq: {url: http://wpa.qq.com/msgrd?v=3&uin=2813116148&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/zhenwen66
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChatQR.jpg
  wechatSQ: /img/custom/donate/WeChatSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: eIPnwzcAPKEgqX2PdYhNT8MQ-gzGzoHsz
v_appKey: sfGDeDsrIX9MiTw9AQWkJBPu

